#pragma once
#include <string>
#include <vector>
std::string currentDate();
std::string inputDate(bool& exit);
bool cinFailCheck();
void dateFileEditing(const std::string name, double dailyCalories);
char stringToChar(const std::string string, bool& fail);
void allProfilesFileCreation();
void searchProfileName(bool& exit, std::string& profile);
bool failCheck(bool fail);
bool failedInput(bool& fail);
bool failIntegerInput(const std::string string, bool& fail);
bool exitCheck(const std::string toCheck, bool& exit);
bool logoutCheck(const std::string toCheck, bool& logout);
bool isStringDouble(const std::string string);
size_t stringLength(const std::string string);
void heightInput(std::string& input, bool& exit, unsigned* height, unsigned int& iter, bool& fail);
void weightInput(std::string& input, bool& exit, double* weight, unsigned int& iter, bool& fail);
void premiumInput(std::string& input, bool& exit, bool* isPremium, unsigned int iter, bool& fail);
bool workoutOrMeal(const std::string input, bool& fail);
int charToInt(const char a);
size_t strLen(std::string string);
bool multipleDotsCheck(std::string string);
double stringToDouble(const std::string string, bool& fail);
int stringToInt(const std::string string, bool& fail);
void startingScreen(bool& fail, bool& exit, unsigned& nextAction);
double BMR(double bmr, const bool gender, const double weight, const double height, const unsigned age);
void dailyNeededCalories(int& dailyCal, double bmr, const bool gender, const double weight, const double height, const double activityLevel, const unsigned age);
void reg(bool& fail, bool& exit, std::string& name, std::string& password, unsigned* userDataUnsigned[], bool* userDataBool[], double* userDataDouble[]);
bool login(bool& fail, bool& exit, std::string& name, std::string& password, unsigned* userDataUnsigned[], bool* userDataBool[], double* userDataDouble[]);
void addAMealToFile(const std::string name, std::string meal, int calories);
void addADailyMeal(const std::string name, int& dailyCalories);
void addADailyWorkout(const std::string name, int& dailyCalories);
void currentDateData(const std::string name);
void specificDateData(const std::string name, bool& exit);
void DisplayDataFromVector(const std::vector<std::string> data, const size_t size);
bool checkForDatestring(const std::string string);
void deleteDataForADate(const std::string name, bool& exit);
void changeDataForToday(const std::string name, bool& exit, bool& fail);
void changePersonalData(unsigned& age, unsigned& goal, unsigned& speedOfWeight, double& weight, double& height, bool& gender, bool& isPremium, bool& logout, bool& exit, bool& fail);
bool generalScreenNextAction(bool& fail, bool& exit, bool& logout, const std::string input, const std::string name, unsigned& age, unsigned& goal, unsigned& speedOfWeight, double& activityLevel, double& weight, double& height, bool& gender, bool& isPremium, int& caloriesIntake, int& caloriesUsed, double bmr, int dailyCalories);
void calculateMacronutriens(const unsigned int goal, int& carbohydrates, const int recommendedCalorieIntake, int& fat, int& protein, int& carbohydratesGrams, int& proteinGrams, int& fatGrams);
void displayMacronutrients(const int recommendedCalorieIntake, const unsigned goal, bool& exit, bool& logout);
void dailyCalorieScreen(const std::string name, bool& fail, bool& exit, bool& logout, int& dailyCalories, const double goal, const double speedOfWeight, const double activityLevel, const int bmr, const double isPremium);
void dailyCaloriesTillNow(const std::string name, int& dailyCalories, bool& fail);
void recommendedCalories(int& recommendedCalories, const unsigned speedOfWeight, const unsigned goal, const double activityLevel, const int bmr);
void generalScreen(bool& fail, bool& exit, bool& logout, const std::string name, unsigned& age, unsigned& goal, unsigned& speedOfWeight, double& weight, double& height, double& activityLevel, bool& isPremium, bool& gender, int& caloriesIntake, int& caloriesUsed, int dailyCalories);
