void menuSeparator();
bool logoutOrExitCheck(std::string input, bool& exit, bool& logout);
void failedInput();
bool startingScreen(bool& exit, bool& logout);
void yesOrNo(std::string input, bool& fail, bool& nameIsGood);
void nameInput(std::string& name, bool& exit, bool& logout);
void passwordInput(std::string& password, bool& exit, bool& logout);
void doesProfileExistReg(std::string& name, bool& exit, bool& logout);
void doesProfileExistLogin(std::string name, bool& exit, bool& logout);
void loadData(const std::string name, std::string& password, unsigned* unsignedDataArray[], double* doubleDataArray[], bool* boolDataArray[]);
bool isUnsigned(const std::string str);
void ageInput(unsigned* age, bool& exit, bool& logout);
void heightInput(unsigned* height, bool& exit, bool& logout);
void goalInput(unsigned* goal, bool& exit, bool& logout);
void weightInput(double* weight, bool& exit, bool& logout);
void activityLevelInput(double* activityLevel, bool& exit, bool& logout);
void speedOfWeightInput(double* speedOfWeight, bool& exit, bool& logout);
void genderInput(bool* gender, bool& exit, bool& logout);
void premiumInput(bool* isPremium, bool& exit, bool& logout);
bool isDouble(const std::string str);
void newUserFileCreation(const std::string name, const std::string password,unsigned* unsignedDataArray[],double* doubleDataArray[],bool* boolDataArray[]);